import { mkdir, mkdtemp, rm, stat, writeFile, copyFile, readFile, readdir } from 'node:fs/promises';
import path from 'node:path';
import { tmpdir } from 'node:os';
import { pathToFileURL } from 'node:url';
import { spawn } from 'node:child_process';
import { requireMember } from '@/lib/auth';
import { assertInsideRoot, getDriveMetadata, getDriveMediaFetch } from '@/lib/drive';
import { getIndexedResourceShell } from '@/lib/indexed-resource';
import { PPTX_MIME } from '@/lib/presentation-pdf';
import { parseSingleByteRange } from '@/lib/range-requests';
import { privacySafeRequestKey, rateLimit } from '@/lib/rate-limit';

export const runtime='nodejs';
export const dynamic='force-dynamic';
const cacheRoot=path.join(tmpdir(),'dp-presentation-pdf-cache');
const inFlight=new Map<string,Promise<string>>();
const failures=new Map<string,{message:string;at:number}>();
const MIN_PDF_BYTES=1024;
const CONVERSION_TIMEOUT_MS=180_000;
const FAILURE_TTL_MS=5*60*1000;

function safeKey(fileId:string,modified:string){return `${fileId}-${modified||'unknown'}`.replace(/[^a-zA-Z0-9._-]/g,'_');}
function cachePath(key:string){return path.join(cacheRoot,`${key}.pdf`);}
async function validPdf(file:string){try{const buf=await readFile(file); return buf.length>=MIN_PDF_BYTES && buf.subarray(0,5).toString('utf8')==='%PDF-';}catch{return false;}}
async function findGeneratedPdf(dir:string){const direct=path.join(dir,'input.pdf'); if(await validPdf(direct))return direct; const files=await readdir(dir).catch(()=>[]); for(const file of files){if(file.toLowerCase().endsWith('.pdf')){const candidate=path.join(dir,file); if(await validPdf(candidate))return candidate;}} throw new Error('Converted PDF was not created or failed validation');}
function runOffice(command:string,args:string[],profileDir:string,inputDir:string,label:string){return new Promise<void>((resolve,reject)=>{let stdout=''; let stderr=''; const p=spawn(command,args,{shell:false,cwd:inputDir,stdio:['ignore','pipe','pipe'],env:{...process.env,HOME:profileDir,SAL_USE_VCLPLUGIN:'svp'}}); const timer=setTimeout(()=>{p.kill('SIGKILL'); reject(new Error(`${command} ${label} timed out`));},CONVERSION_TIMEOUT_MS); p.stdout.on('data',d=>{stdout=(stdout+d.toString()).slice(-8000);}); p.stderr.on('data',d=>{stderr=(stderr+d.toString()).slice(-8000);}); p.on('error',err=>{clearTimeout(timer); reject(new Error(`${command} ${label} failed to start: ${err.message}`));}); p.on('exit',c=>{clearTimeout(timer); c===0?resolve():reject(new Error(`${command} ${label} failed ${c}: ${stdout} ${stderr}`));});});}
function officeArgs(input:string,inputDir:string,profileDir:string,convertTo:string){return ['--headless','--invisible','--nologo','--nodefault','--nofirststartwizard','--nolockcheck',`-env:UserInstallation=${pathToFileURL(profileDir).href}`,'--convert-to',convertTo,'--outdir',inputDir,input];}
async function convertWithLibreOffice(input:string,inputDir:string,profileDir:string){const attempts=[{label:'impress_pdf_Export',convertTo:'pdf:impress_pdf_Export'},{label:'generic_pdf',convertTo:'pdf'}]; const errors:string[]=[]; for(const attempt of attempts){for(const command of ['soffice','libreoffice']){try{await runOffice(command,officeArgs(input,inputDir,profileDir,attempt.convertTo),profileDir,inputDir,attempt.label); return await findGeneratedPdf(inputDir);}catch(error){errors.push(error instanceof Error?error.message:String(error));}}} throw new Error(errors.join('\n---\n'));}
async function convert(fileId:string,modified:string){const key=safeKey(fileId,modified); const out=cachePath(key); if(await validPdf(out))return out; const existing=inFlight.get(key); if(existing)return existing; const promise=(async()=>{await mkdir(cacheRoot,{recursive:true}); const inputDir=await mkdtemp(path.join(tmpdir(),'dp-pptx-input-')); const profileDir=await mkdtemp(path.join(tmpdir(),'dp-pptx-profile-')); try{const input=path.join(inputDir,'input.pptx'); const res=await getDriveMediaFetch(fileId); if(!res.ok)throw new Error(`Drive download failed: ${res.status} ${await res.text().catch(()=>'')}`); const bytes=Buffer.from(await res.arrayBuffer()); if(bytes.length<1024)throw new Error(`Downloaded PPTX is too small: ${bytes.length} bytes`); await writeFile(input, bytes); const generated=await convertWithLibreOffice(input,inputDir,profileDir); await copyFile(generated,out); failures.delete(key); return out;} finally {inFlight.delete(key); await Promise.allSettled([rm(inputDir,{recursive:true,force:true}),rm(profileDir,{recursive:true,force:true})]);}})(); inFlight.set(key,promise); return promise;}
function recentFailure(key:string){const failure=failures.get(key); if(!failure)return null; if(Date.now()-failure.at>FAILURE_TTL_MS){failures.delete(key); return null;} return failure;}
async function conversionStatus(fileId:string,modified:string){const key=safeKey(fileId,modified); if(await validPdf(cachePath(key)))return {status:'ready' as const,key}; const failure=recentFailure(key); if(failure)return {status:'failed' as const,key,message:failure.message}; if(inFlight.has(key))return {status:'processing' as const,key}; return {status:'idle' as const,key};}
function startConversionInBackground(fileId:string,modified:string){const key=safeKey(fileId,modified); if(inFlight.has(key))return; convert(fileId,modified).catch(error=>{const message=error instanceof Error?error.message:String(error); failures.set(key,{message,at:Date.now()}); console.error('PPTX preview conversion failed', { fileId, message });});}
function jsonStatus(body:unknown,status=200){return Response.json(body,{status,headers:{'cache-control':'no-store','vary':'Cookie','retry-after':'2'}});}
async function servePdf(req:Request,pdf:string,fileId:string,modified:string){const st=await stat(pdf); const size=st.size; const etag=`"pptx-${safeKey(fileId,modified||String(st.mtimeMs))}-${size}"`; const base={'content-type':'application/pdf','cache-control':'private, max-age=86400','vary':'Cookie','accept-ranges':'bytes','etag':etag}; const requestedRange=req.headers.get('range'); if(!requestedRange && req.headers.get('if-none-match')===etag)return new Response(null,{status:304,headers:base}); const range=parseSingleByteRange(requestedRange,size); if(range.kind==='invalid')return new Response(null,{status:416,headers:{...base,'content-range':`bytes */${size}`}}); const buf=await readFile(pdf); if(range.kind==='range'){const body=buf.subarray(range.start,range.end+1); return new Response(body,{status:206,headers:{...base,'content-length':String(body.length),'content-range':`bytes ${range.start}-${range.end}/${size}`}});} return new Response(buf,{headers:{...base,'content-length':String(size)}});}

export async function GET(req:Request,{params}:{params:Promise<{fileId:string}>}){await requireMember(); const {fileId}=await params; const limited=await rateLimit(privacySafeRequestKey(req,'presentation-pdf'),120,10*60*1000,'presentation-pdf'); if(!limited.ok)return new Response('Too many requests. Please try again later.',{status:429}); const indexedMeta=await getIndexedResourceShell(fileId); if(!indexedMeta&&!(await assertInsideRoot(fileId)))return new Response('Not found',{status:404}); const meta=indexedMeta||await getDriveMetadata(fileId); if(!meta||meta.isFolder||!(meta.mimeType===PPTX_MIME||/\.pptx$/i.test(meta.name)))return new Response('Not found',{status:404}); const modified=meta.modifiedTime||''; const state=await conversionStatus(fileId,modified); if(state.status==='ready')return servePdf(req,cachePath(state.key),fileId,modified); if(state.status==='failed')return jsonStatus({status:'failed'},502); startConversionInBackground(fileId,modified); return jsonStatus({status:'processing'},202);}
