import { mkdir, mkdtemp, rm, stat, writeFile, copyFile, readFile, readdir } from 'node:fs/promises';
import path from 'node:path';
import { tmpdir } from 'node:os';
import { pathToFileURL } from 'node:url';
import { spawn } from 'node:child_process';
import { requireMember } from '@/lib/auth';
import { assertInsideRoot, getDriveMetadata, getDriveMediaFetch } from '@/lib/drive';
import { getIndexedResourceShell } from '@/lib/indexed-resource';
import { PPTX_MIME } from '@/lib/presentation-pdf';
import { parseSingleByteRange } from '@/lib/range-requests';
import { privacySafeRequestKey, rateLimit } from '@/lib/rate-limit';

export const runtime='nodejs';
export const dynamic='force-dynamic';
const cacheRoot=path.join(tmpdir(),'dp-presentation-pdf-cache');
const inFlight=new Map<string,Promise<string>>();
const MIN_PDF_BYTES=1024;
const CONVERSION_TIMEOUT_MS=90_000;

function safeKey(fileId:string,modified:string){return `${fileId}-${modified||'unknown'}`.replace(/[^a-zA-Z0-9._-]/g,'_');}
async function validPdf(file:string){try{const buf=await readFile(file); return buf.length>=MIN_PDF_BYTES && buf.subarray(0,5).toString('utf8')==='%PDF-';}catch{return false;}}
async function findGeneratedPdf(dir:string){const direct=path.join(dir,'input.pdf'); if(await validPdf(direct))return direct; const files=await readdir(dir).catch(()=>[]); for(const file of files){if(file.toLowerCase().endsWith('.pdf')){const candidate=path.join(dir,file); if(await validPdf(candidate))return candidate;}} throw new Error('Converted PDF was not created or failed validation');}
function runOffice(command:string,args:string[],profileDir:string,inputDir:string){return new Promise<void>((resolve,reject)=>{let stdout=''; let stderr=''; const p=spawn(command,args,{shell:false,cwd:inputDir,stdio:['ignore','pipe','pipe'],env:{...process.env,HOME:profileDir,SAL_USE_VCLPLUGIN:'svp'}}); const timer=setTimeout(()=>{p.kill('SIGKILL'); reject(new Error(`${command} conversion timed out`));},CONVERSION_TIMEOUT_MS); p.stdout.on('data',d=>{stdout=(stdout+d.toString()).slice(-8000);}); p.stderr.on('data',d=>{stderr=(stderr+d.toString()).slice(-8000);}); p.on('error',err=>{clearTimeout(timer); reject(new Error(`${command} failed to start: ${err.message}`));}); p.on('exit',c=>{clearTimeout(timer); c===0?resolve():reject(new Error(`${command} conversion failed ${c}: ${stdout} ${stderr}`));});});}
async function convertWithLibreOffice(input:string,inputDir:string,profileDir:string){const args=['--headless','--invisible','--nologo','--nodefault','--nofirststartwizard','--nolockcheck',`-env:UserInstallation=${pathToFileURL(profileDir).href}`,'--convert-to','pdf:impress_pdf_Export','--outdir',inputDir,input]; const errors:string[]=[]; for(const command of ['soffice','libreoffice']){try{await runOffice(command,args,profileDir,inputDir); return await findGeneratedPdf(inputDir);}catch(error){errors.push(error instanceof Error?error.message:String(error));}} throw new Error(errors.join('\n---\n'));}
async function convert(fileId:string,modified:string){const key=safeKey(fileId,modified); const out=path.join(cacheRoot,`${key}.pdf`); if(await validPdf(out))return out; const existing=inFlight.get(key); if(existing)return existing; const promise=(async()=>{await mkdir(cacheRoot,{recursive:true}); const inputDir=await mkdtemp(path.join(tmpdir(),'dp-pptx-input-')); const profileDir=await mkdtemp(path.join(tmpdir(),'dp-pptx-profile-')); try{const input=path.join(inputDir,'input.pptx'); const res=await getDriveMediaFetch(fileId); if(!res.ok)throw new Error(`Drive download failed: ${res.status} ${await res.text().catch(()=>'')}`); const bytes=Buffer.from(await res.arrayBuffer()); if(bytes.length<1024)throw new Error(`Downloaded PPTX is too small: ${bytes.length} bytes`); await writeFile(input, bytes); const generated=await convertWithLibreOffice(input,inputDir,profileDir); await copyFile(generated,out); return out;} finally {inFlight.delete(key); await Promise.allSettled([rm(inputDir,{recursive:true,force:true}),rm(profileDir,{recursive:true,force:true})]);}})(); inFlight.set(key,promise); return promise;}
export async function GET(req:Request,{params}:{params:Promise<{fileId:string}>}){await requireMember(); const {fileId}=await params; const limited=await rateLimit(privacySafeRequestKey(req,'presentation-pdf'),60,10*60*1000,'presentation-pdf'); if(!limited.ok)return new Response('Too many requests. Please try again later.',{status:429}); const indexedMeta=await getIndexedResourceShell(fileId); if(!indexedMeta&&!(await assertInsideRoot(fileId)))return new Response('Not found',{status:404}); const meta=indexedMeta||await getDriveMetadata(fileId); if(!meta||meta.isFolder||!(meta.mimeType===PPTX_MIME||/\.pptx$/i.test(meta.name)))return new Response('Not found',{status:404}); try{const pdf=await convert(fileId,meta.modifiedTime||''); const st=await stat(pdf); const size=st.size; const etag=`"pptx-${safeKey(fileId,meta.modifiedTime||String(st.mtimeMs))}-${size}"`; const base={'content-type':'application/pdf','cache-control':'private, max-age=86400','vary':'Cookie','accept-ranges':'bytes','etag':etag}; const requestedRange=req.headers.get('range'); if(!requestedRange && req.headers.get('if-none-match')===etag)return new Response(null,{status:304,headers:base}); const range=parseSingleByteRange(requestedRange,size); if(range.kind==='invalid')return new Response(null,{status:416,headers:{...base,'content-range':`bytes */${size}`}}); const buf=await readFile(pdf); if(range.kind==='range'){const body=buf.subarray(range.start,range.end+1); return new Response(body,{status:206,headers:{...base,'content-length':String(body.length),'content-range':`bytes ${range.start}-${range.end}/${size}`}});} return new Response(buf,{headers:{...base,'content-length':String(size)}});}catch(error){console.error('PPTX preview conversion failed', { fileId, message: error instanceof Error ? error.message : String(error) }); return new Response('Preview unavailable',{status:502});}}
