export const dynamic = 'force-dynamic';
export const fetchCache = 'force-no-store';

import Link from 'next/link';
import { Nav } from '@/components/nav';
import { requireAdmin } from '@/lib/auth';
import { applyActivityFilters } from '@/lib/admin-filters';
import { isDriveConfigured } from '@/lib/drive';
import { getIndexSyncStatus } from '@/lib/index-sync';
import { IndexSyncPanel } from './index-sync-panel';
import { createSupabaseAdminClient, isSupabaseConfigured } from '@/lib/supabase';
import type { ActivityLog, ResourceMembership, ResourceReport, SupportTicket } from '@/lib/types';

const statuses=['open','in_review','resolved','closed'];
function n(v?:string){const x=Number(v||1);return Number.isFinite(x)&&x>0?x:1} function size(v?:string,d=25){const x=Number(v||d);return [25,50,100].includes(x)?x:d}
function statusRank(s:string){return s==='open'?0:s==='in_review'?1:s==='resolved'?2:3}
function badge(s:string){return <span className="rounded bg-slate-100 px-2 py-0.5 text-xs font-medium capitalize text-slate-700">{s.replace('_',' ')}</span>}
function pager(base:Record<string,string|undefined>,key:string,page:number,total:number,per:number){const pages=Math.max(1,Math.ceil(total/per));return <div className="flex items-center justify-end gap-2 p-2 text-xs text-slate-500"><span>Page {page} of {pages}</span>{page>1&&<Link href={{query:{...base,[key]:String(page-1)}}} className="rounded border px-2 py-1">Previous</Link>}{page<pages&&<Link href={{query:{...base,[key]:String(page+1)}}} className="rounded border px-2 py-1">Next</Link>}</div>}
function QueueFilters({prefix,sp}:{prefix:string;sp:Record<string,string|undefined>}){return <form className="mb-3 grid gap-2 md:grid-cols-6"><select name={`${prefix}Status`} defaultValue={sp[`${prefix}Status`]||''} className="rounded-md border border-slate-300 bg-white p-2 text-sm"><option value="">Any status</option>{statuses.map(s=><option key={s} value={s}>{s.replace('_',' ')}</option>)}</select><input name={`${prefix}Email`} defaultValue={sp[`${prefix}Email`]||''} placeholder="Reporter email" className="rounded-md border border-slate-300 bg-white p-2 text-sm"/><input name={`${prefix}Search`} defaultValue={sp[`${prefix}Search`]||''} placeholder="Resource, subject, or path" className="rounded-md border border-slate-300 bg-white p-2 text-sm"/><input type="date" name={`${prefix}From`} defaultValue={sp[`${prefix}From`]||''} className="rounded-md border border-slate-300 bg-white p-2 text-sm"/><input type="date" name={`${prefix}To`} defaultValue={sp[`${prefix}To`]||''} className="rounded-md border border-slate-300 bg-white p-2 text-sm"/><button className="rounded-md bg-slate-950 px-3 py-2 text-sm font-medium text-white">Filter</button></form>}

export default async function Admin({ searchParams }: { searchParams: Promise<Record<string, string | undefined>> }) {
  const { membership } = await requireAdmin(); const sp = await searchParams; const sb = createSupabaseAdminClient();
  const userPage=n(sp.userPage), activityPage=n(sp.activityPage), reportPage=n(sp.reportPage), ticketPage=n(sp.ticketPage); const userSize=size(sp.userSize,25); const pageSize=25;
  let usersQ=sb.from('dp_resource_memberships').select('*',{count:'exact'}).order('created_at',{ascending:false}); if(sp.userEmail) usersQ=usersQ.ilike('email',`%${sp.userEmail}%`); if(sp.role) usersQ=usersQ.eq('role',sp.role); const {data:memberships=[],count:userCount=0,error:membershipsError}=await usersQ.range((userPage-1)*userSize,userPage*userSize-1); if(membershipsError) throw new Error(membershipsError.message);
  let activityQuery=sb.from('dp_resource_activity_logs').select('*',{count:'exact'}).order('created_at',{ascending:false}); activityQuery=applyActivityFilters(activityQuery,sp); const {data:logs=[],count:activityCount=0,error:logsError}=await activityQuery.range((activityPage-1)*50,activityPage*50-1); if(logsError) throw new Error(logsError.message);
  async function queue(table:'dp_resource_reports'|'dp_support_tickets', prefix:string, page:number){let q=sb.from(table).select('*',{count:'exact'}); if(sp[`${prefix}Status`]) q=q.eq('status',sp[`${prefix}Status`]); if(sp[`${prefix}Email`]) q=q.ilike('reporter_email',`%${sp[`${prefix}Email`]}%`); if(sp[`${prefix}From`]) q=q.gte('created_at',sp[`${prefix}From`]); if(sp[`${prefix}To`]) q=q.lte('created_at',`${sp[`${prefix}To`]}T23:59:59`); q=q.order('created_at',{ascending:false}).range((page-1)*pageSize,page*pageSize-1); const r=await q; let data=(r.data||[]) as any[]; const term=(sp[`${prefix}Search`]||'').toLowerCase(); if(term)data=data.filter(x=>[x.resource_name,x.resource_path,x.subject,x.category].some(v=>String(v||'').toLowerCase().includes(term))); data.sort((a,b)=>statusRank(a.status)-statusRank(b.status)||String(b.created_at).localeCompare(String(a.created_at))); return {data,count:r.count||data.length};}
  const [{data:reports,count:reportCount},{data:tickets,count:ticketCount},indexStatus]=await Promise.all([queue('dp_resource_reports','report',reportPage),queue('dp_support_tickets','ticket',ticketPage),getIndexSyncStatus()]);
  const exportQuery = new URLSearchParams(Object.entries(sp).filter(([, v]) => v) as [string, string][]).toString(); const activityLabel=(action:string)=>({folder_opened:'Opened folder',file_opened:'Opened file',download_started:'Started download'}[action]||action);
  return <><Nav admin={membership.role==='admin'} email={membership.email}/><main className="mx-auto max-w-7xl px-4 py-6 sm:px-6 lg:px-8"><h1 className="text-xl font-semibold tracking-tight text-[color:var(--dp-navy)]">Admin operations</h1><nav className="mt-4 flex flex-wrap gap-4 border-b border-slate-200 text-sm" aria-label="Admin sections">{['Library index','Resource reports','Support tickets','Users','Activity'].map(tab=><a key={tab} href={`#${tab.toLowerCase().replaceAll(' ','-')}`} className="border-b-2 border-transparent py-2 text-slate-600 hover:border-[color:var(--dp-blue)] hover:text-[color:var(--dp-navy)]">{tab}</a>)}</nav>{!isSupabaseConfigured()?<p className="mt-4 border border-amber-200 bg-amber-50 p-4 text-amber-900">Supabase is not configured.</p>:null}{!isDriveConfigured()?<p className="mt-4 border border-amber-200 bg-amber-50 p-4 text-amber-900">Google Drive is not configured.</p>:null}<section id="library-index" className="mt-5"><IndexSyncPanel initial={indexStatus}/></section>
  <section id="resource-reports" className="mt-8"><h2 className="text-base font-semibold">Resource reports</h2><QueueFilters prefix="report" sp={sp}/><div className="overflow-x-auto border-y border-slate-200 bg-white"><table className="min-w-full text-sm"><thead className="bg-slate-50 text-left text-xs uppercase text-slate-500"><tr><th className="p-2">Status</th><th className="p-2">Category</th><th className="p-2">Resource</th><th className="p-2">Reporter</th><th className="p-2">Submitted</th><th className="p-2">Assigned</th><th className="p-2">Actions</th></tr></thead><tbody>{(reports as ResourceReport[]).map(r=><tr key={r.id} className="border-t"><td className="p-2">{badge(r.status)}</td><td className="p-2">{r.category}</td><td className="p-2 max-w-72 truncate">{r.resource_name}<p className="text-xs text-slate-500">{r.resource_path}</p></td><td className="p-2">{r.reporter_email}</td><td className="p-2">{new Date(r.created_at).toLocaleString()}</td><td className="p-2">{(r as any).assigned_to?'Assigned':'Unassigned'}</td><td className="p-2"><details><summary className="cursor-pointer font-medium text-[color:var(--dp-blue)]">Inspect</summary><form action={`/api/admin/reports/${r.id}`} method="post" className="mt-2 grid gap-2 rounded border bg-slate-50 p-3"><p>{r.message}</p>{r.drive_file_id&&<Link href={`/resource/${r.drive_file_id}`} target="_blank" className="font-medium text-[color:var(--dp-navy)]">Preview resource</Link>}<textarea name="internal_notes" placeholder="Internal notes" defaultValue={(r as any).internal_notes||''}/><textarea name="resolution_note" placeholder="Resolution note" defaultValue={(r as any).resolution_note||''}/><select name="status" defaultValue={r.status}>{statuses.map(s=><option key={s}>{s}</option>)}</select></form></details></td></tr>)}</tbody></table>{pager(sp,'reportPage',reportPage,reportCount,pageSize)}</div></section>
  <section id="support-tickets" className="mt-8"><h2 className="text-base font-semibold">Support tickets</h2><QueueFilters prefix="ticket" sp={sp}/><div className="overflow-x-auto border-y border-slate-200 bg-white"><table className="min-w-full text-sm"><thead className="bg-slate-50 text-left text-xs uppercase text-slate-500"><tr><th className="p-2">Status</th><th className="p-2">Category</th><th className="p-2">Subject</th><th className="p-2">Reporter</th><th className="p-2">Submitted</th><th className="p-2">Assigned</th><th className="p-2">Actions</th></tr></thead><tbody>{(tickets as SupportTicket[]).map(t=><tr key={t.id} className="border-t"><td className="p-2">{badge(t.status)}</td><td className="p-2">{t.category}</td><td className="p-2 max-w-72 truncate">{t.subject}</td><td className="p-2">{t.reporter_email}</td><td className="p-2">{new Date(t.created_at).toLocaleString()}</td><td className="p-2">{(t as any).assigned_to?'Assigned':'Unassigned'}</td><td className="p-2"><details><summary className="cursor-pointer font-medium text-[color:var(--dp-blue)]">Inspect</summary><div className="mt-2 rounded border bg-slate-50 p-3"><p>{t.message}</p><p className="text-xs text-slate-500">Use admin API to update status, assignment, notes, and resolution.</p></div></details></td></tr>)}</tbody></table>{pager(sp,'ticketPage',ticketPage,ticketCount,pageSize)}</div></section>
  <section id="users" className="mt-8"><h2 className="text-base font-semibold">Users</h2><form className="mt-3 grid gap-2 md:grid-cols-5"><input name="userEmail" defaultValue={sp.userEmail||''} placeholder="Email search" className="rounded-md border p-2 text-sm"/><select name="role" defaultValue={sp.role||''} className="rounded-md border p-2 text-sm"><option value="">Any role</option><option>user</option><option>admin</option></select><select name="userSize" defaultValue={String(userSize)} className="rounded-md border p-2 text-sm"><option>25</option><option>50</option><option>100</option></select><button className="rounded-md bg-slate-950 px-3 py-2 text-sm text-white">Filter</button></form><div className="mt-3 border-y bg-white">{(memberships as ResourceMembership[]).map(u=><div key={u.id} className="grid gap-2 border-b p-3 text-sm md:grid-cols-[1fr_100px_160px_120px]"><b>{u.email}</b><span>{u.role}</span><span>{new Date(u.created_at).toLocaleDateString()}</span><span>{u.is_approved?'Approved':'Awaiting approval'}</span></div>)}{pager(sp,'userPage',userPage,userCount||0,userSize)}</div></section>
  <section id="activity" className="mt-8"><h2 className="text-base font-semibold">Activity</h2><form className="mt-3 grid gap-2 md:grid-cols-6"><input name="email" defaultValue={sp.email||''} placeholder="User email" className="rounded-md border p-2 text-sm"/><input name="file" defaultValue={sp.file||''} placeholder="Resource" className="rounded-md border p-2 text-sm"/><select name="action" defaultValue={sp.action||''} className="rounded-md border p-2 text-sm"><option value="">Any action</option><option>folder_opened</option><option>file_opened</option><option>download_started</option></select><input type="date" name="from" defaultValue={sp.from||''} className="rounded-md border p-2 text-sm"/><input type="date" name="to" defaultValue={sp.to||''} className="rounded-md border p-2 text-sm"/><button className="rounded-md bg-slate-950 px-3 py-2 text-sm text-white">Filter</button></form><a className="mt-3 inline-block text-sm font-medium text-amber-800" href={`/api/admin/activity/export?${exportQuery}`}>Export CSV</a><div className="mt-3 overflow-x-auto border bg-white"><table className="min-w-full text-sm"><tbody>{(logs as ActivityLog[]).map(log=><tr key={log.id} className="border-t"><td className="p-2 text-slate-500">{new Date(log.created_at).toLocaleString()}</td><td className="p-2 font-medium">{log.user_email}</td><td className="p-2">{activityLabel(log.action)}</td><td className="p-2">{log.file_name||'Resource'}</td></tr>)}</tbody></table>{pager(sp,'activityPage',activityPage,activityCount||0,50)}</div></section></main></>;
}
