'use client';
import Link from 'next/link';
import { useEffect, useRef, useState } from 'react';
import { ChevronDown, Shield, UserRound, LogOut } from 'lucide-react';

export function AccountMenu({ admin=false, email }: { admin?: boolean; email?: string | null }) {
  const [open,setOpen]=useState(false); const ref=useRef<HTMLDivElement>(null);
  useEffect(()=>{const h=(e:MouseEvent)=>{if(ref.current&&!ref.current.contains(e.target as Node))setOpen(false)}; const k=(e:KeyboardEvent)=>{if(e.key==='Escape')setOpen(false)}; document.addEventListener('mousedown',h); document.addEventListener('keydown',k); return()=>{document.removeEventListener('mousedown',h);document.removeEventListener('keydown',k)}},[]);
  return <div ref={ref} className="relative"><button type="button" aria-haspopup="menu" aria-expanded={open} onClick={()=>setOpen(!open)} className="inline-flex h-9 items-center gap-2 rounded-md border border-slate-200 bg-white px-2.5 text-sm text-slate-700 hover:bg-slate-50"><span className="grid size-6 place-items-center rounded bg-[color:var(--dp-navy)] text-xs font-semibold text-white">{email?.[0]?.toUpperCase()||'D'}</span><span className="hidden max-w-44 truncate lg:inline">{email||'Account'}</span><ChevronDown className="size-4 text-slate-500"/></button>{open&&<div role="menu" className="absolute right-0 z-50 mt-2 w-64 overflow-hidden rounded-md border border-slate-200 bg-white py-1 shadow-xl"><div className="border-b border-slate-100 px-3 py-2"><p className="text-xs uppercase tracking-wide text-slate-500">Signed in</p><p className="truncate text-sm font-medium text-[color:var(--dp-navy)]">{email}</p></div><Link role="menuitem" href="/profile" className="flex items-center gap-2 px-3 py-2 text-sm hover:bg-blue-50" onClick={()=>setOpen(false)}><UserRound className="size-4"/>Profile</Link>{admin&&<Link role="menuitem" href="/admin" className="flex items-center gap-2 px-3 py-2 text-sm hover:bg-blue-50" onClick={()=>setOpen(false)}><Shield className="size-4"/>Admin</Link>}<form action="/api/auth/signout" method="post"><button role="menuitem" className="flex w-full items-center gap-2 px-3 py-2 text-left text-sm hover:bg-blue-50"><LogOut className="size-4"/>Sign out</button></form></div>}</div>
}
