'use client';
import { useEffect, useMemo, useState } from 'react';
import { ExternalLink, ZoomIn, ZoomOut } from 'lucide-react';
import { ResourceActions } from '@/components/resource-actions';
const ROW_LIMIT=500;
export function ResourcePreview({fileId,mimeType,name}:{fileId:string;mimeType:string;name:string}){const url=`/api/resource/${fileId}/content`; const [zoom,setZoom]=useState(1); if(mimeType.includes('pdf')) return <PdfViewer url={url} fileId={fileId} name={name}/>; if(mimeType.startsWith('image/')) return <div className="relative grid min-h-[70vh] place-items-center overflow-auto rounded-xl border bg-[color:var(--dp-navy)] p-4"><div className="absolute bottom-4 left-1/2 z-10 flex -translate-x-1/2 gap-2 rounded-xl bg-[color:var(--dp-warm-surface)]/95 p-2 shadow"><button aria-label="Zoom out" onClick={()=>setZoom(z=>Math.max(.5,z-.1))}><ZoomOut/></button><button aria-label="Zoom in" onClick={()=>setZoom(z=>z+.1)}><ZoomIn/></button></div><img src={url} alt={name} style={{transform:`scale(${zoom})`}} className="max-h-[70vh] max-w-full object-contain transition"/></div>; if(mimeType.includes('spreadsheet')||name.match(/\.(xlsx?)$/i)) return <Spreadsheet url={url} />; if(mimeType.includes('csv')||name.match(/\.csv$/i)) return <CsvTable url={url}/>; if(mimeType.startsWith('text/')) return <TextPreview url={url}/>; if(mimeType.includes('word')||name.endsWith('.docx')) return <DocxPreview url={url}/>; return <div className="border border-slate-200 bg-white p-8 text-center">Preview unavailable for this file type.</div>}
function Toolbar({url,fileId,name}:{url:string;fileId:string;name:string}){return <div className="flex flex-wrap items-center gap-2"><a aria-label={`Open ${name} in a new tab`} className="rounded-md border border-slate-200 bg-white px-3 py-1.5 text-sm text-slate-700 hover:bg-slate-50" target="_blank" href={url}>Open in new tab <ExternalLink className="inline size-4"/></a><ResourceActions resource={{driveFileId:fileId,resourceName:name,resourcePath:'Resource preview'}} downloadHref={`/api/files/${fileId}/download`}/></div>}
function PdfViewer({url,fileId,name}:{url:string;fileId:string;name:string}){const [page,setPage]=useState(1),[pages,setPages]=useState(1),[zoom,setZoom]=useState(1),[state,setState]=useState('Loading PDF preview…'); useEffect(()=>{let ok=true; import('pdfjs-dist').then(pdfjs=>{pdfjs.GlobalWorkerOptions.workerSrc='/pdf.worker.min.mjs'; return pdfjs.getDocument({url}).promise}).then(pdf=>{if(!ok)return; setPages(pdf.numPages); setState('PDF loaded. Use the protected viewer controls below.');}).catch(()=>setState('Unable to load the PDF preview.')); return()=>{ok=false}},[url]); useEffect(()=>{const h=(e:KeyboardEvent)=>{if(e.key==='ArrowLeft')setPage(p=>Math.max(1,p-1)); if(e.key==='ArrowRight')setPage(p=>Math.min(pages,p+1));}; addEventListener('keydown',h); return()=>removeEventListener('keydown',h)},[pages]); return <div className="border border-slate-200 bg-white p-3"><Toolbar url={url} fileId={fileId} name={name}/><div className="mt-3 flex flex-wrap items-center gap-2"><button onClick={()=>setPage(p=>Math.max(1,p-1))}>Previous</button><span>Page {page} of {pages}</span><button onClick={()=>setPage(p=>Math.min(pages,p+1))}>Next</button><button onClick={()=>setZoom(z=>Math.max(.5,z-.1))}>Zoom out</button><button onClick={()=>setZoom(z=>z+.1)}>Zoom in</button><button onClick={()=>setZoom(1)}>Fit width</button></div><p className="mt-2 text-sm text-[color:var(--dp-ink)]/60">{state}</p><iframe title={name} src={`${url}#page=${page}&zoom=${Math.round(zoom*100)}`} className="mt-3 h-[72vh] w-full border bg-slate-50"/></div>}
function Spreadsheet({url}:{url:string}){const [sheets,setSheets]=useState<string[]>([]),[active,setActive]=useState(''),[rows,setRows]=useState<any[][]>([]),[q,setQ]=useState(''),[trunc,setTrunc]=useState(false); useEffect(()=>{import('xlsx').then(XLSX=>fetch(url).then(r=>r.arrayBuffer()).then(buf=>{const wb=XLSX.read(buf,{type:'array',cellFormula:false,bookVBA:false}); setSheets(wb.SheetNames); const n=wb.SheetNames[0]; setActive(n); const data=XLSX.utils.sheet_to_json(wb.Sheets[n],{header:1,raw:false,defval:''}) as any[][]; setTrunc(data.length>ROW_LIMIT); setRows(data.slice(0,ROW_LIMIT));}).catch(()=>setRows([['Preview unavailable for this workbook.']])) )},[url]); const shown=useMemo(()=>q?rows.filter(r=>r.join(' ').toLowerCase().includes(q.toLowerCase())):rows,[rows,q]); return <div className="border border-slate-200 bg-white p-4"><p className="text-sm text-[color:var(--dp-ink)]/60">Formulas, macros, and external connections are never executed.</p>{trunc&&<p className="mt-2 rounded bg-amber-50 p-2 text-sm text-amber-900">Large workbook — previewing the first 500 rows.</p>}<select aria-label="Sheet selector" value={active} onChange={e=>setActive(e.target.value)} className="mt-3 rounded border p-2">{sheets.map(s=><option key={s}>{s}</option>)}</select><input aria-label="Search selected sheet" placeholder="Search selected sheet" value={q} onChange={e=>setQ(e.target.value)} className="ml-2 rounded border p-2"/><Table rows={shown}/></div>}
function CsvTable({url}:{url:string}){const [rows,setRows]=useState<string[][]>([]); useEffect(()=>{fetch(url).then(r=>r.text()).then(t=>setRows(t.split(/\r?\n/).slice(0,ROW_LIMIT).map(l=>l.split(',')))).catch(()=>setRows([['CSV preview unavailable']]))},[url]); return <div className="border border-slate-200 bg-white p-4"><p className="mb-2 text-sm text-[color:var(--dp-ink)]/60">Sortable CSV table preview.</p><Table rows={rows}/></div>}
function Table({rows}:{rows:any[][]}){return <div className="mt-3 max-h-[70vh] overflow-auto"><table className="min-w-full text-sm"><thead className="sticky top-0 bg-slate-100"><tr>{(rows[0]||[]).map((c,i)=><th key={i} className="border p-2 text-left">{c||`Column ${i+1}`}</th>)}</tr></thead><tbody>{rows.slice(1).map((r,i)=><tr key={i}>{(rows[0]||r).map((_,j)=><td key={j} className="border p-2">{r[j]}</td>)}</tr>)}</tbody></table></div>}
function TextPreview({url}:{url:string}){const [text,setText]=useState('Loading preview…'); useEffect(()=>{fetch(url).then(r=>r.text()).then(t=>setText(t.slice(0,200000))).catch(()=>setText('Preview unavailable.'))},[url]); return <pre className="max-h-[75vh] overflow-auto border border-slate-200 bg-white p-4 text-sm">{text}</pre>}
function DocxPreview({url}:{url:string}){const [html,setHtml]=useState('Loading document preview…'); useEffect(()=>{import('mammoth').then(m=>fetch(url).then(r=>r.arrayBuffer()).then(buf=>m.convertToHtml({arrayBuffer:buf})).then(res=>setHtml(res.value.replace(/<script[\s\S]*?<\/script>/gi,''))).catch(()=>setHtml('<p>Preview unavailable for this document. Download remains available. DOCX rendering can vary and never executes macros.</p>')))},[url]); return <div className="prose max-w-none border border-slate-200 bg-white p-6" dangerouslySetInnerHTML={{__html:html}}/>}
