'use client';
import { useEffect, useRef, useState } from 'react';

type Result = { id: string; email: string; role: string; joined_at?: string | null; latest_activity_at?: string | null };
const inputClass = 'mt-1 h-9 w-full rounded-md border border-stone-300 bg-[color:var(--dp-warm-surface)] px-3 text-sm text-slate-800 outline-none focus-visible:border-stone-400 focus-visible:bg-white';

export function EmailSearchInput({ label, value, onChange, placeholder = 'Search by email' }: { label: string; value: string; onChange: (value: string) => void; placeholder?: string }) {
  const [open, setOpen] = useState(false); const [loading, setLoading] = useState(false); const [results, setResults] = useState<Result[]>([]); const [active, setActive] = useState(-1); const box = useRef<HTMLLabelElement>(null);
  useEffect(() => { const onDoc = (e: MouseEvent) => { if (box.current && !box.current.contains(e.target as Node)) setOpen(false); }; document.addEventListener('mousedown', onDoc); return () => document.removeEventListener('mousedown', onDoc); }, []);
  useEffect(() => { const q = value.trim(); if (q.length < 2) { setResults([]); setOpen(false); return; } const ac = new AbortController(); const t = setTimeout(async () => { setLoading(true); try { const res = await fetch(`/api/admin/users/search?q=${encodeURIComponent(q)}`, { signal: ac.signal }); const json = await res.json().catch(() => ({ users: [] })); setResults(res.ok ? json.users || [] : []); setOpen(res.ok); setActive(-1); } catch { if (!ac.signal.aborted) setResults([]); } finally { if (!ac.signal.aborted) setLoading(false); } }, 300); return () => { ac.abort(); clearTimeout(t); }; }, [value]);
  function choose(r: Result) { onChange(r.email); setOpen(false); }
  return <label ref={box} className="relative block text-xs font-semibold text-slate-600">{label}<input value={value} placeholder={placeholder} onChange={e => onChange(e.target.value)} onFocus={() => value.trim().length >= 2 && setOpen(true)} onKeyDown={e => { if (!open) return; if (e.key === 'Escape') setOpen(false); if (e.key === 'ArrowDown') { e.preventDefault(); setActive(i => Math.min(results.length - 1, i + 1)); } if (e.key === 'ArrowUp') { e.preventDefault(); setActive(i => Math.max(0, i - 1)); } if (e.key === 'Enter' && active >= 0 && results[active]) { e.preventDefault(); choose(results[active]); } }} className={inputClass} />{loading && <span className="absolute right-2 top-8 text-[11px] font-normal text-slate-400">Searching…</span>}{open && results.length > 0 && <div className="absolute z-30 mt-1 max-h-56 w-full overflow-auto rounded-md border border-stone-200 bg-white py-1 shadow-lg">{results.map((r, i) => <button key={r.id} type="button" onMouseDown={e => e.preventDefault()} onClick={() => choose(r)} className={`block w-full px-3 py-2 text-left text-sm ${i === active ? 'bg-blue-50' : 'hover:bg-slate-50'}`}><span className="font-medium text-slate-800">{r.email}</span><span className="ml-2 text-xs capitalize text-slate-500">{r.role}</span></button>)}</div>}</label>;
}
